# Generated by Django 3.0.8 on 2021-02-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewboard', '0002_auto_20210208_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extenduser',
        ),
    ]
