# Generated by Django 3.0.8 on 2021-02-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewboard', '0004_extenduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='github',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='instagram',
            field=models.CharField(max_length=2200, null=True),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='photo',
            field=models.ImageField(blank=True, default='https://t4.ftcdn.net/jpg/03/46/93/61/360_F_346936114_RaxE6OQogebgAWTalE1myseY1Hbb5qPM.jpg', null=True, upload_to='users'),
        ),
    ]
