# Generated by Django 3.0.8 on 2021-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewboard', '0005_auto_20210209_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
