# Generated by Django 3.0.8 on 2021-02-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewboard', '0006_auto_20210209_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extenduser',
        ),
    ]
