# Generated by Django 3.0.8 on 2021-02-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewboard', '0007_delete_extenduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='extenduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=2200, null=True)),
                ('github', models.CharField(max_length=2048, null=True)),
                ('linkedin', models.CharField(max_length=2000)),
                ('photo', models.ImageField(blank=True, default='https://t4.ftcdn.net/jpg/03/46/93/61/360_F_346936114_RaxE6OQogebgAWTalE1myseY1Hbb5qPM.jpg', null=True, upload_to='users')),
                ('post_pref', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
